[shell]
program = "zsh"
args = ["-l"]

[window]
dimensions = { columns = 150, lines = 28 }
title = "a7lavinraj@mark-42"
padding.x = 10
padding.y = 10
# decorations = "none"
# opacity = 0.8

[font]
normal = { family = "DejaVuSansM Nerd Font" }
size = 11

[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'
