# Default colors
[colors.primary]
background = '#0F111A'
foreground = '#c4c7d1'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#F07178'
green   = '#C3E88D'
yellow  = '#FFCB6B'
blue    = '#80cbc4'
magenta = '#6c71c4'
cyan    = '#89DDFF'
white   = '#EEFFFF'

# Bright colors
[colors.bright]
black   = '#35434d'
red     = '#DC6068'
green   = '#C3E88D'
yellow  = '#FFCB6B'
blue    = '#6E98EB'
magenta = '#6c71c4'
cyan    = '#71C6E7'
white   = '#EEFFFF'

[font]
normal.family = "NotoSansM Nerd Font"
italic.style = "Regular"
bold.style = "Regular"
bold_italic.style = "Regular"
size = 14

[window]
padding.x = 10
padding.y = 5
decorations = "None"

[cursor]
thickness = 0.3
