# Neovim based settings.
set-option -g default-terminal "screen-256color"
set-option -sg escape-time 10
set-option -sa terminal-features ',xterm-256color:RGB'

# Prefix key.
unbind C-b
set -g prefix C-n

# Some usefull keybinds.
unbind %
unbind '"'
unbind r
unbind -T copy-mode-vi MouseDragEnd1Pane

bind r source-file ~/.tmux.conf
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# General settings.
set -g mouse on
set-window-option -g mode-keys vi
# set -g status-position top

# Plugin.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin 'tmux-plugins/tmux-sensible'

# Tmux-minimal theme configurations.
set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @minimal-tmux-bg "#82aaff"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-indicator-str "    "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "bottom"

run '~/.tmux/plugins/tpm/tpm'

run '~/.tmux/plugins/tpm/tpm'
run -b '~/.tmux/plugins/tpm/tpm'
