set-option -a terminal-features "alacritty:RGB"
set-option -a terminal-overrides "alacritty:Tc"
set-option -g focus-events on

set -g status-style bg=default,fg=default
set -g status-left ""
set -g window-status-style dim
set -g message-style fg=default,bg=default
set -g window-status-current-style fg="#ff9e64",bg=default

bind -n M-R source-file ~/coding/dotfiles/.tmux.conf
bind -n M-H previous-window
bind -n M-L next-window
bind -n M-N new-window

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"

run "~/.tmux/plugins/tpm/tpm"
