set -g default-terminal "alacritty" 
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",alacritty*:Tc" 
set-option -sg escape-time 10

unbind %
unbind '"'
unbind r
unbind -T copy-mode-vi MouseDragEnd1Pane

bind r source-file ~/.tmux.conf
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# General settings.
set -g mouse on
set-window-option -g mode-keys vi

# Plugin.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Tmux-minimal theme configurations.
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-bg "none"
set -g @minimal-tmux-fg "#FF0000"
set -g @minimal-tmux-justify "left"
set -g @minimal-tmux-status "bottom"

run '~/.tmux/plugins/tpm/tpm'
