add_newline = true
command_timeout = 200
format = "[$directory]($style)$line_break$character"

[directory]
truncation_length = 2
truncation_symbol = ".../"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
